### ISSUE TITLE
Customise heading levels? 

### ISSUE THREAD

**Issue by carltongibson** [matthiask/django-prose-editor#12]
Hi @matthiask. 

Sometimes (maybe) five levels of headings is more than one needs. Sometimes (maybe) you want to allow (say) h2-h5 but not h1. 

Would it be possible to allow customisation there? (Beyond removing `heading` from `types` entirely.)

Thanks.

**Comment by matthiask** [comment]
Hi @carltongibson 

I agree! The schema doesn't constrain heading levels much currently and I think I'd like to keep it that way:
https://github.com/ProseMirror/prosemirror-schema-basic/blob/4e358f5443f15abe09406c9327e35aa9e3c1bf8c/src/schema-basic.ts#L42-L54

I'm working on the editor right now (for other reasons) and I have submitted a PR here:
https://github.com/matthiask/django-prose-editor/pull/13

Would that address your issue?

**Comment by carltongibson** [comment]
> Would that address your issue?

I think that would be more than fine! Just controlling the menu is sufficient for real-world cases I think! 💃

**Comment by matthiask** [comment]
Thanks! I'll upload a release today or tomorrow.
