### ISSUE TITLE
Is there support for code blocks (pre and code tags) and their formatting?

### ISSUE THREAD

**Issue by interglobalmedia** [matthiask/django-prose-editor#17]
Hi,

Is there support for code blocks (pre and code tags) and their formatting? This editor works seamlessly with my Django site, but I can't  seem to add code blocks in the markdown. Am I missing something or is there some way for a workaround? Being able to create large blocks of code in my markdown on my site is a must. Thanks!

**Comment by matthiask** [comment]
Hi

This wouldn't be impossible to add, ProseMirror has a code block out of the box:
https://prosemirror.net/

A nicer variant is this:
https://prosemirror.net/examples/codemirror/

django-prose-editor currently doesn't support a code block, but adding the node to the standard schema would be straightforward.

**Comment by interglobalmedia** [comment]
Thanks @matthiask!

**Comment by matthiask** [comment]
django-prose-editor 0.10 (only available as alpha pre-releases) has been rebuilt on top of tiptap, see https://406.ch/writing/rebuilding-django-prose-editor-from-the-ground-up/

Tiptap has a `Code` mark which should be relatively easy to integrate:
https://tiptap.dev/docs/editor/extensions/marks/code

You have to define your own editor for that:
https://github.com/matthiask/django-prose-editor?tab=readme-ov-file#customization
