### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by SaarWolf** [matthiask/django-prose-editor#21]
This is more a question than an issue: I set the background color in a form to a light gray to get a better focus on the form elements.

All widgets now have a white input area - the django-prose-editor changes the text area to light grey as the forms background. I'm not real firm with css and am searching for the one value to change the text area to the bg color of the other widgets.

![Bildschirmfoto_20241220_133907](https://github.com/user-attachments/assets/0241aaef-4d75-4072-844f-c212eb9fce37)

Btw: I like this editor, because it has just the things I need and therefore it is simple to use.

**Comment by matthiask** [comment]
Hi @SaarWolf 

Thank you! The intention was that the color of `--prose-editor-background` (which defaults to `#fff`) would automatically be applied to the editing area. I fixed the CSS so that this happens now. You have to update to 0.10.2 though.

**Comment by SaarWolf** [comment]
Hi @matthiask 

Thank your very much!

**Comment by SaarWolf** [comment]
Ooops. Color is correct but the buttons are gone. 

![Bildschirmfoto_20241220_145706](https://github.com/user-attachments/assets/3664304c-26fd-4397-acfe-13c56946b3ce)

**Comment by matthiask** [comment]
Hmm, that's sad. Do you get any JavaScript errors in the console?

If you're using the `ProseEditor(Form)Field` or the `ProseEditorWidget` things should "just" work. I did a complete rewrite (see https://406.ch/writing/rebuilding-django-prose-editor-from-the-ground-up/), so some breakage is expected when using undocumented API, but at least you should get errors somewhere, not silent failure.

**Comment by SaarWolf** [comment]
Ok, I get the following errors:

VM532 de.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'define')
    at VM532 de.js:3:106
    at VM532 de.js:3:774
(anonym) @ VM532 de.js:3
(anonym) @ VM532 de.js:3
VM537 de.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'define')
    at VM537 de.js:3:106
    at VM537 de.js:3:774
(anonym) @ VM537 de.js:3
(anonym) @ VM537 de.js:3
de.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'define')
    at de.js:3:106
    at de.js:3:774
(anonym) @ de.js:3
(anonym) @ de.js:3
VM549 default.js:1 Uncaught TypeError: DjangoProseEditor.initializeEditors is not a function
    at VM549 default.js:1:901
    at VM549 default.js:1:933
(anonym) @ VM549 default.js:1
(anonym) @ VM549 default.js:1
VM551 default.js:1 Uncaught TypeError: DjangoProseEditor.initializeEditors is not a function
    at VM551 default.js:1:901
    at VM551 default.js:1:933
(anonym) @ VM551 default.js:1
(anonym) @ VM551 default.js:1
default.js:1 Uncaught TypeError: DjangoProseEditor.initializeEditors is not a function
    at default.js:1:901
    at default.js:1:933

**Comment by matthiask** [comment]
Can you show me the contents of `de.js`? `de.js` seems to have a problem with `define()`, but `define` doesn't even exist in django-prose-editor's assets. 

Also, which browser are you using? I avoid using ES modules for now even though I really want to because browser support for importmaps isn't there yet.

**Comment by SaarWolf** [comment]
Where should I find the relevant de.js? In staticfiles I find this one for django-select2:

/*! Select2 4.0.13 | https://github.com/select2/select2/blob/master/LICENSE.md */

!function(){if(jQuery&&jQuery.fn&&jQuery.fn.select2&&jQuery.fn.select2.amd)var e=jQuery.fn.select2.amd;e.define("select2/i18n/de",[],function(){return{errorLoading:function(){return"Die Ergebnisse konnten nicht geladen werden."},inputTooLong:function(e){return"Bitte "+(e.input.length-e.maximum)+" Zeichen weniger eingeben"},inputTooShort:function(e){return"Bitte "+(e.minimum-e.input.length)+" Zeichen mehr eingeben"},loadingMore:function(){return"Lade mehr Ergebnisse…"},maximumSelected:function(e){var n="Sie können nur "+e.maximum+" Element";return 1!=e.maximum&&(n+="e"),n+=" auswählen"},noResults:function(){return"Keine Übereinstimmungen gefunden"},searching:function(){return"Suche…"},removeAllItems:function(){return"Entferne alle Elemente"}}}),e.define,e.require}();
